### ISSUE TITLE
gateway运行提示系统找不到指定文件，虽然不影响正常运行，但是看着不舒服

### ISSUE THREAD

**Issue by liuzhixin405** [duyanming/Viper#14]
![Snipaste_2022-09-25_20-27-37](https://user-images.githubusercontent.com/30038237/192150001-bc741e4f-9e48-4cd4-a8ac-01b5f599cd69.png)
这个应该是aspnetcore框架的问题吧

**Comment by duyanming** [comment]
viper 网关不会用到的，直接引提示的文件试试
