### ISSUE TITLE
发布viperservice出现.netframework找不到问题

### ISSUE THREAD

**Issue by pakehexiunv** [duyanming/Viper#15]
用的.net6来发布，因为要部署到LinuxARM64服务器上，不能使用.net6框架来运行吗
![image](https://user-images.githubusercontent.com/115833691/200789216-de9827db-a5bb-41c9-8f64-4f5d6eb905ca.png)

**Comment by duyanming** [comment]
里面设置了多目标编译，直接移除framework相关的东西就可以
