### ISSUE TITLE
just like "Anno.EngineData.RateLimit","Anno.EngineData.Cache" these are not open source?

### ISSUE THREAD

**Issue by chenbigit** [duyanming/Viper#2]
just like "Anno.EngineData.RateLimit","Anno.EngineData.Cache" these are not open source?

**Comment by duyanming** [comment]
代码在这里:https://github.com/duyanming/Anno.LRUCache
涉及Anno的代码会逐步开源

**Comment by chenbigit** [comment]
That‘s great. Cheers
