### ISSUE TITLE
按照demo就错了

### ISSUE THREAD

**Issue by gxlqssjf** [duyanming/Viper#5]
![image](https://user-images.githubusercontent.com/1277598/100562266-16c0a680-32f6-11eb-8438-99ca70003dd0.png)

**Comment by gxlqssjf** [comment]
![image](https://user-images.githubusercontent.com/1277598/100562278-24762c00-32f6-11eb-8180-6e453e848cb4.png)

**Comment by duyanming** [comment]
拉取最新版viper试试，这个问题是autofac 最新版和旧版本的不兼容造成的

**Comment by gxlqssjf** [comment]
好，我试试先

**Comment by gxlqssjf** [comment]
> 拉取最新版viper试试，这个问题是autofac 最新版和旧版本的不兼容造成的

弄一个docker部署的运行试试，因为现在基本都在docker里面运行的了

**Comment by gxlqssjf** [comment]
> 拉取最新版viper试试，这个问题是autofac 最新版和旧版本的不兼容造成的

https://github.com/duyanming/Viper/issues/5#issuecomment-737230584
请问你试了没？已经拉了还是一样啊

**Comment by gxlqssjf** [comment]
> 拉取最新版viper试试，这个问题是autofac 最新版和旧版本的不兼容造成的
![image](https://user-images.githubusercontent.com/1277598/100951836-4e279100-354a-11eb-93d0-d8d26b020580.png)
问题还是一样啊，请问你试过了吗？

**Comment by duyanming** [comment]
我刚刚升级了下Anno的依赖包，修复了泛型注入的BUG。请获取Viper最新代码

**Comment by duyanming** [comment]
> > 拉取最新版viper试试，这个问题是autofac 最新版和旧版本的不兼容造成的
> > ![image](https://user-images.githubusercontent.com/1277598/100951836-4e279100-354a-11eb-93d0-d8d26b020580.png)
> > 问题还是一样啊，请问你试过了吗？

问题已解决，获取最新代码。欢迎加QQ群：478399354。
