### ISSUE TITLE
 强烈建议增加日志服务

### ISSUE THREAD

**Issue by 52017126** [duyanming/Viper#6]
强烈建议增加日志服务，一个API执行时，里面肯定写了不少日志, 在API结束时 不仅记录链路信息，同时把这个API里记录的日志也附加到链路信息里，这样查问题，那就方便多了。

**Comment by duyanming** [comment]
非常感谢你的建议，用户日志附加到链路追踪信息里面确实可以进一步方便排查问题。
链路追踪是：系统级别的
日志是：用户级别的
我找时间补充一下。

**Comment by duyanming** [comment]
![image](https://user-images.githubusercontent.com/17999146/107142496-50530500-696a-11eb-8bdb-9c9e3b1aff53.png)
