### ISSUE TITLE
您好，对这个viper网关比较迷惑

### ISSUE THREAD

**Issue by valiantzhao** [duyanming/Viper#7]
类似MvcCallAnno 项目没走网关吧，要网关还得加一层是吗，看代码viper像是对微服务的一个集合。

**Comment by duyanming** [comment]
微服务中内部调用一般是走rpc (socket) ，对外部走http api网关然后到集群。网关主要是应对外部调用集群。
对于公司内部 比如我们有一些传统项目，或者说历史项目(例如就是你说的MvcCallAnno)想借助集群的部分功能，这时候MvcCallAnno扮演一个客户端的角色就可以通过安装nuget包走rpc直接调用集群而不通过API网关，性能更高，调用方式更优雅。

**Comment by duyanming** [comment]
https://www.cnblogs.com/duyanming/p/14029063.html
之前写的博客。

**Comment by valiantzhao** [comment]
好的，谢谢
