### ISSUE TITLE
Connection open error . Retrieval of the RSA public key is not enabled for insecure connections

### ISSUE THREAD

**Issue by seamusic** [duyanming/Viper#8]
第一步，启动vipcenter；正常
第二步，修改数据库连接，启动ViperService；正常，成功注册服务；
第三步，启动Viper.GetWay，正常，访问地址是：http://localhost:5000/
然后登录的时候提示：
English Message : Connection open error . Retrieval of the RSA public key is not enabled for insecure connections. Chinese Message : 连接数据库过程中发生错误，检查服务器是否正常连接字符串是否正确，实在找不到原因请先Google错误信息：Retrieval of the RSA public key is not enabled for insecure connections..

请问有可能是哪里出现问题了呢？

**Comment by duyanming** [comment]
连接数据库出错了，你看下Viperservice 下面配置文件 数据库链接字符串对面，

**Comment by duyanming** [comment]
连接数据库的url中，加上allowPublicKeyRetrieval=true参数
或者 ConnectionString的SslMode=none;改为SslMode=Preferred;
参考这里试试:
https://blog.csdn.net/Yuriey/article/details/80423504
